//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorSwipe
    {
        public string C_DoorAccessPostDateTime_ { get; set; }
        public string C_TRAN_ID_ { get; set; }
        public string C_MC_TRANSEQNUM_ { get; set; }
        public string C_ISONLINE_ { get; set; }
        public string C_VALIDATION_TYPE_ { get; set; }
        public string C_ACTUALDATETIME_ { get; set; }
        public string C_POSTDATETIME_ { get; set; }
        public string C_TENDER_TYPE_ID_ { get; set; }
        public string C_DOOR_ID_ { get; set; }
        public string C_CUST_IDENTIFICATION_TYPE_ { get; set; }
        public string C_CUST_ID_ { get; set; }
        public string C_MASTERCONTROLLER_ID_ { get; set; }
        public string C_HOSTCOMP_ID_ { get; set; }
    }
}
