//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Door
    {
        public string C_DOOR_ID_ { get; set; }
        public string C_MASTERCONTROLLER_ID_ { get; set; }
        public string C_ADDRESS_ { get; set; }
        public string C_MERCHANT_ID_ { get; set; }
        public string C_DOOR_IDENTIFIER_ { get; set; }
        public string C_DESCRIPTION_ { get; set; }
        public string C_BUILDING_ID_ { get; set; }
        public string C_AREA_ID_ { get; set; }
        public string C_DOOR_GROUP_ID_ { get; set; }
        public string C_USE_DOOR_DEFAULT_ { get; set; }
        public string C_DOOR_UNLOCK_TIME_SECONDS_ { get; set; }
        public string C_MIN_SIREN_TIME_SECONDS_ { get; set; }
        public string C_HELD_ALARM_TYPE_ { get; set; }
        public string C_HELD_ALARM_DELAY_TIME_SECONDS_ { get; set; }
        public string C_FORCE_ALARM_TYPE_ { get; set; }
        public string C_FORCE_ALARM_DELAY_TIME_SECONDS_ { get; set; }
        public string C_USE_DOOR_DEFAULT_SCHEDULE_ { get; set; }
        public string C_SCHEDULE_ID_ { get; set; }
        public string C_OFFLINE_OPERATION_TYPE_ { get; set; }
        public string C_ALARM_INSTRUCTIONS_ { get; set; }
    }
}
